default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_142_gentle_man_development

test:
  <<: *default
  database: protospace_142_gentle_man_test


production:
  <<: *default
  database: protospace_142_gentle_man_production
  username: protospace_142_gentle_man
  password: <%= ENV['PROTOSPACE_142_gentle_man_DATABASE_PASSWORD'] %>
